version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          command: chrome -v
      - store_test_results:
          path: /tmp/test-results
workflows:
  e2e-test:
    jobs:
      - test